import assert from 'node:assert/strict';
const db=new Map();globalThis.localStorage={getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)};
const w=await import('../../prototypes/shared/workflow-store.js');
let s=w.initial();s.writingMethod.mode='prompt';s.writingMethod.text='共用写作指令';
assert.deepEqual(w.taskSnapshot(s,'novelRevision').method,s.writingMethod,'故事导演必须继承写作方法');
s.scriptMethod.text='共用剧本指令';assert.deepEqual(w.taskSnapshot(s,'scriptRefine').method,s.scriptMethod);
assert.equal(typeof w.setGeneration,'function');w.setGeneration(s,{aspect:'16:9',resolution:'4K',model:'selected'});
assert.equal(w.taskSnapshot(s,'video').aspect,'16:9');assert.equal(s.finishing.resolution,'4K');
w.selectNovel(s,w.makeTopic(s,0));w.buildScript(s,true);w.reviewScript(s);w.confirmScript(s);s.shots=w.makeShots(s);
s.shots.forEach(sh=>{sh.assets.forEach(a=>{a.image='image';a.confirmed=true});sh.dialogues=[{id:w.uid('line'),speaker:sh.speaker,emotion:sh.emotion,text:sh.dialogue,voice:'voice'}]});s.boardScriptId=s.final.id;s.boardVersion=1;w.boardReview(s);w.applyReport(s);w.boardReview(s);s.boardConfirmed=s.boardVersion;s.shots.forEach(sh=>sh.assets.forEach(a=>a.confirmed=true));
assert.equal(typeof w.bindPreviousFrame,'function');const first=s.shots[0],second=s.shots[1];
assert.throws(()=>w.bindPreviousFrame(s,second.id,{id:'f1',sourceVideoId:'v1',image:'frame'}));
first.video={id:'v1',lastFrame:{id:'f1',sourceVideoId:'v1',image:'frame'}};
w.bindPreviousFrame(s,second.id,first.video.lastFrame);w.bindPreviousFrame(s,second.id,first.video.lastFrame);
assert.equal(w.refs(second.prompt).filter(id=>id==='f1').length,1,'重复点击不能重复插入');
assert.deepEqual(w.validateRefs(second),[]);assert.equal(w.makeVideoSnapshot(s,second,'independent').previousVideoId,'v1');
first.video={id:'v2',lastFrame:{id:'f2',sourceVideoId:'v2',image:'new frame'}};
assert.throws(()=>w.makeVideoSnapshot(s,second,'independent'),'前镜更换后拒绝旧引用');
w.bindPreviousFrame(s,second.id,first.video.lastFrame);assert.ok(!w.refs(second.prompt).includes('f1'));assert.ok(w.refs(second.prompt).includes('f2'));
second.video={id:'second'};w.invalidateChain(s,0);assert.equal(second.previousFrameStale,true);assert.equal(second.videoStale,true);
console.log('PASS: shared method snapshots, project/output specs, precise/idempotent previous-frame binding and stale dependencies.');
const q=w.initial();w.setGeneration(q,{aspect:'9:16',resolution:'1080P'});w.selectNovel(q,w.makeTopic(q,0));w.buildScript(q);w.reviewScript(q);
assert.ok(q.scriptReport.issues.length);assert.doesNotThrow(()=>w.confirmScript(q),'AI 质检发现问题也可确认剧本');assert.ok(q.scriptReport.issues.length,'用户继续不得伪造质检通过');assert.equal(q.reviewDecisions.at(-1).choice,'keep_current');
q.scriptReport=null;assert.doesNotThrow(()=>w.confirmScript(q),'没有报告也能继续');q.scriptDraft.text=' ';assert.throws(()=>w.confirmScript(q),'空剧本仍不能执行');q.scriptDraft.text=q.final.text;
q.shots=w.makeShots(q);q.boardVersion=1;q.boardScriptId=q.final.id;q.shots.forEach(sh=>{sh.dialogues=[{id:w.uid('line'),text:sh.dialogue,speaker:sh.speaker,emotion:sh.emotion,voice:'default'}];sh.assets.forEach(a=>{a.image='image';a.confirmed=true})});q.shots.forEach(sh=>sh.assets.forEach(a=>a.image=null));assert.doesNotThrow(()=>w.confirmBoard(q),'确认分镜应早于图片生成，不要求已有图片');q.shots.forEach(sh=>sh.assets.forEach(a=>a.image='image'));w.boardReview(q);assert.ok(q.report.issues.length);assert.doesNotThrow(()=>w.confirmBoard(q));assert.equal(w.generationReady(q),true);assert.ok(q.report.issues.length);q.report=null;assert.doesNotThrow(()=>w.confirmBoard(q));q.shots[0].prompt='@[missing]';assert.throws(()=>w.confirmBoard(q),'无法解析的输入仍不能执行');
console.log('PASS: advisory QC never blocks valid content; continuation recorded without altering reports; invalid execution inputs remain rejected.');
