import assert from 'node:assert/strict';
import {modelGroup,resolveModel,validateModel,resolvePrompt} from '../../prototypes/shared/configuration-model.js';
const model=name=>({name,provider:'test',url:'https://example.test/api',capability:'text',timeout:120});
const s={models:{script:model('legacy')},modelDefaults:{text:model('default'),audio:{...model('audio'),capability:'audio'}},defaults:{review:'fallback'}};
assert.equal(resolveModel(s,'novel').name,'default');assert.equal(resolveModel(s,'script').name,'legacy');assert.equal(resolveModel(s,'voice').name,'audio');assert.equal(resolveModel(s,'music').name,'audio');
const frozen=resolveModel(s,'novel');s.modelDefaults.text.name='changed';assert.equal(frozen.name,'default');delete s.models.script;assert.equal(resolveModel(s,'script').name,'changed');assert.equal(modelGroup('blockingImage'),'image');assert.equal(modelGroup('voicePreset'),'text');assert.throws(()=>validateModel(model('bad'),'audio'));
const h={config:{promptBindings:{review:'custom'}},methodLibrary:[{id:'custom',interactionKey:'review',text:'custom text',version:2}]};assert.equal(resolvePrompt(s,h,'review').text,'custom text');s.methodOverrides={custom:{text:'project'}};assert.equal(resolvePrompt(s,h,'review').text,'project');delete s.methodOverrides.custom;assert.equal(resolvePrompt(s,h,'review').text,'custom text');console.log('PASS: category inheritance, legacy override, restore, audio isolation, frozen model and scenario template resolution.');
const db=new Map();globalThis.localStorage={getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)};
const w=await import('../../prototypes/shared/workflow-store.js');const state=w.read(),library=w.hub();library.config.modelDefaults={text:model('route')};library.config.promptBindings={review:'review-choice'};library.methodLibrary.push({id:'review-choice',kind:'prompt',interactionKey:'review',name:'检查模板',text:'检查 {{script}} {{shots}}',version:3});w.putHub(library);const current=w.read();const snapshot=w.taskSnapshot(current,'review');assert.equal(snapshot.model.name,'route');assert.equal(snapshot.promptTemplate.resourceId,'review-choice');current.projectPromptBindings={review:'prompt-review'};current.methodOverrides={'prompt-review':{text:'项目覆盖',version:5}};w.write(current);assert.equal(w.taskSnapshot(w.read(),'review').prompt,'项目覆盖');assert.equal(w.taskSnapshot(w.read(),'review').promptTemplate.overrideVersion,5);assert.equal(snapshot.prompt,'检查 {{script}} {{shots}}');console.log('PASS: effective configuration in task snapshots and project scenario override survives reload.');
