import assert from 'node:assert/strict';
import {importSchema,importTemplate,validateImport,composeShot,shotSpec} from '../../prototypes/shared/shot-contract.js';
const copy=x=>structuredClone(x);assert.equal(validateImport(copy(importTemplate)).shots.length,1);
for(const mutate of [v=>v.schemaVersion=2,v=>v.shots[0].duration=0,v=>v.shots[0].generation={aspect:'4:3'},v=>v.shots[0].assets[0].image='https://bad',v=>v.shots[0].bindings.assetIds=[],v=>v.shots[0].bindings.dialogueIds=['missing'],v=>v.shots.push(copy(v.shots[0])),v=>v.shots[0].dialogues[0].id=v.shots[0].id,v=>v.shots[0].prompt+=' @[missing]']){const v=copy(importTemplate);mutate(v);assert.throws(()=>validateImport(v));}
const s={styles:[{name:'古风',text:'水墨构图，柔和侧光，古代服饰。'}],styleIndex:0,styleVersion:2,generation:{model:'模型A',aspect:'9:16',resolution:'1080P'}},sh=copy(importTemplate.shots[0]);const prompt=composeShot(s,sh);assert.ok(prompt.prompt.includes(s.styles[0].text));assert.ok(prompt.prompt.includes(sh.dialogues[0].text));assert.deepEqual(prompt.bindings.dialogueIds,['line-1']);sh.dialogues[0].text='新台词';assert.ok(composeShot(s,sh).prompt.includes('新台词'));assert.ok(!prompt.prompt.includes('新台词'));sh.generation={aspect:'16:9',model:'模型B'};assert.equal(shotSpec(s,sh).model,'模型B');assert.equal(shotSpec(s,sh).resolution,'1080P');
const db=new Map();globalThis.localStorage={getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)};globalThis.document={documentElement:{dataset:{}}};globalThis.window={addEventListener(){}};
const w=await import('../../prototypes/shared/workflow-store.js');const {C}=await import('../../prototypes/shared/studio-ui.js');const {generateSpeech}=await import('../../prototypes/shared/studio-director.js');const state=w.initial();state.shots=[sh];C.s=state;sh.dialogues.push({id:'line-2',text:'',speaker:'旁白',emotion:'自然',voice:'默认'});await generateSpeech(sh,'line-1');assert.ok(sh.dialogues[0].audio);assert.equal(sh.dialogues[1].audio,undefined);assert.equal(state.jobs[0].input.lineId,'line-1');
const snap=w.makeVideoSnapshot({...state,...s},sh,'independent');assert.equal(snap.model.name,'模型B');assert.equal(snap.aspect,'16:9');assert.ok(snap.prompt.includes('水墨构图'));assert.equal(snap.dialogues.length,2);
console.log('PASS V13: strict import shape/IDs/bindings, per-line TTS isolation, style/dialogue compilation and single-shot spec snapshots.');
