const themeKey='mengyuan-prototype-theme';
const themes={light:'浅色',dark:'深色',sky:'晴空蓝'};
let selectedTheme='dark';
try{const stored=localStorage.getItem(themeKey);if(Object.hasOwn(themes,stored))selectedTheme=stored}catch{}
document.documentElement.dataset.theme=selectedTheme;
export const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function shell({active='components',content=''}){
const steps=[['creation','创意'],['story','故事'],['script','剧本'],['storyboard','分镜'],['finishing','导出']];
const flow=steps.some(x=>x[0]===active);
const links=[['projects','项目'],['creation','创作'],['assets','资产'],['tasks','任务记录'],['settings','系统设置']];
return `<div class="app-shell"><header class="topbar"><div class="brand"><svg class="workshop-mark" viewBox="0 0 32 32" aria-hidden="true"><path d="M5 5a3 3 0 0 1 4.5-2.6l20 11a3 3 0 0 1 0 5.2l-20 11A3 3 0 0 1 5 27Z" fill="currentColor" opacity=".22"/><path d="M9 8a2 2 0 0 1 3-1.7l14 8a2 2 0 0 1 0 3.4l-14 8A2 2 0 0 1 9 24Z" fill="currentColor"/><path d="m13 12 8 4-8 4Z" fill="white"/></svg><strong class="workshop-name">AI短片工坊</strong></div><div class="header-actions"><button class="button menu-toggle" id="menu-toggle">展开导航</button><span class="helper">本地交互演示</span>${['components','states'].includes(active)?'<a class="button" href="./settings.html" data-nav="settings">提示词</a>':'<button class="button" id="global-config">提示词</button>'}<label class="theme-picker" for="ui-theme"><span class="theme-dot" aria-hidden="true"></span>UI主题<select id="ui-theme" aria-label="UI主题">${Object.entries(themes).map(([value,name])=>`<option value="${value}" ${value===selectedTheme?'selected':''}>${name}</option>`).join('')}</select></label></div></header><div class="shell-body"><aside class="sidebar" aria-label="主导航">${links.map(([id,t],i)=>`<a href="./${id}.html" data-nav="${id}" class="nav-link ${(active===id||(id==='creation'&&flow))?'active':''}"><span>${['▦','◇','▧','≡','⚙'][i]}</span>${t}</a>`).join('')}<div class="sidebar-note">让每一个故事<br>成为可见的作品。<p>项目独立保存 · 本地演示</p></div></aside><main class="page">${flow?`<nav class="studio-steps" aria-label="创作步骤">${steps.map(([id,t],i)=>`<a class="nav-link ${active===id?'active':''}" href="./${id}.html" data-nav="${id}"><span>${i+1}</span>${t}</a>`).join('')}</nav>`:''}${content}</main></div><div id="toast" class="toast" role="status" hidden></div></div>`}

export function mount(content){document.querySelector('#app').innerHTML=content;document.querySelector('#ui-theme').addEventListener('change',e=>{selectedTheme=e.target.value;document.documentElement.dataset.theme=selectedTheme;try{localStorage.setItem(themeKey,selectedTheme)}catch{}toast(`已切换至${themes[selectedTheme]}主题，当前编辑内容保留`)});document.querySelector('#menu-toggle').addEventListener('click',e=>{const open=document.querySelector('.shell-body').classList.toggle('nav-open');e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.textContent=open?'收起导航':'展开导航'})}
let toastTimer;
export function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},3500)}
export const samplePrompt='请对照原剧本 {{script}} 与分镜 {{shots}}，检查信息遗漏、情绪错位和动作逻辑。逐条给出问题位置、依据和修改建议。';
export function promptDialog(){return `<dialog class="dialog" id="prompt-dialog" aria-labelledby="prompt-title"><div class="panel-header"><div><p class="eyebrow">当前环节 / 分镜质检</p><h2 id="prompt-title">提示词设置</h2></div><button class="button" id="close-prompt" aria-label="关闭提示词设置">关闭</button></div><p class="helper">示例编辑只在当前页面生效，不修改系统默认配置。</p><label class="field" for="prompt-input">质检提示词<textarea id="prompt-input">${esc(samplePrompt)}</textarea></label><p class="helper">可用变量：{{script}} 原剧本、{{shots}} 当前分镜。</p><p class="error-text" id="prompt-error" role="alert" hidden></p><div class="dialog-footer"><button class="button" id="reset-prompt">恢复默认</button><button class="button primary" id="apply-prompt">应用到本次演示</button></div></dialog>`}
export function bindPrompt(){const d=document.querySelector('#prompt-dialog');document.querySelector('#open-prompt').addEventListener('click',()=>d.showModal());document.querySelector('#close-prompt').addEventListener('click',()=>d.close());document.querySelector('#reset-prompt').addEventListener('click',()=>{document.querySelector('#prompt-input').value=samplePrompt;document.querySelector('#prompt-error').hidden=true});document.querySelector('#apply-prompt').addEventListener('click',()=>{const value=document.querySelector('#prompt-input').value;const valid=value.includes('{{script}}')&&value.includes('{{shots}}');const error=document.querySelector('#prompt-error');error.hidden=valid;if(!valid){error.textContent='请保留 {{script}} 与 {{shots}}，才能自动带入对照内容。';return}document.querySelector('#prompt-source').textContent=value===samplePrompt?'继承默认':'本次演示自定义';d.close();toast('已应用提示词；默认配置不受影响')})}
// Plain href remains usable outside the PRD reader. The reader intercepts same-origin data-nav links.

window.addEventListener('storage',e=>{if(e.key===themeKey&&Object.hasOwn(themes,e.newValue)){selectedTheme=e.newValue;document.documentElement.dataset.theme=selectedTheme;const selector=document.querySelector('#ui-theme');if(selector)selector.value=selectedTheme;}});
