export const methodLabels={writingMethod:'写作方法',scriptMethod:'剧本方法',boardMethod:'分镜生成方法'};
export const stageForStep=key=>({novel:'writingMethod',script:'scriptMethod',storyboard:'boardMethod'}[key]||null);
const copy=x=>JSON.parse(JSON.stringify(x));
export function ensureCatalog(h,defaults,steps){
 h.methodLibrary??=[];
 for(const [key,text] of Object.entries(defaults))if(!h.methodLibrary.some(x=>x.id==='prompt-'+key))h.methodLibrary.push({id:'prompt-'+key,kind:'prompt',stage:stageForStep(key),interactionKey:key,name:({novel:'悬念反转故事法',script:'忠于原作改编法',storyboard:'画面节奏分镜法'}[key]||steps[key]+'模板'),text:h.config?.defaults?.[key]||text,version:1,history:[]});
 const seeds=[['writingMethod','人物弧光故事法','先建立人物目标，再写冲突和转折，结尾回应开场。按目标片长限制人物、场景和事件数量。'],['scriptMethod','三幕分场剧本法','将小说改为可拍摄的分场剧本，保留人物动机和情绪转折；每场包含动作、台词和预计时长。'],['boardMethod','连续动作分镜法','逐镜描述动作起止、景别与机位，保持人物朝向、动作因果和前后镜连续；引用图片使用稳定ID。']];
 for(const [stage,name,text] of seeds)if(!h.methodLibrary.some(x=>x.id==='skill-'+stage))h.methodLibrary.push({id:'skill-'+stage,kind:'skill',stage,name,text,version:1,history:[]});
 return h.methodLibrary;
}
export function methodsFor(h,key){return (h.methodLibrary||[]).filter(x=>x.stage===key);}
export function resolveMethod(s,h,key){const old=s[key];if(!old?.resourceId)return old||null;const a=h.methodLibrary?.find(x=>x.id===old.resourceId);if(!a||a.stage!==key)throw Error('方法已不可用，请重新选择');const override=s.methodOverrides?.[a.id];return {resourceId:a.id,name:a.name,mode:a.kind,kind:a.kind,stage:a.stage,interactionKey:a.interactionKey||null,resourceVersion:a.version,version:override?.version||a.version,overrideVersion:override?.version||null,effectiveText:override?.text??a.text,text:override?.text??a.text,source:override?'project':'library'};}
export function selectMethod(s,h,key,id){const a=methodsFor(h,key).find(x=>x.id===id);if(!a)throw Error('该方法不适用于当前环节');s[key]={resourceId:id};s[key]=resolveMethod(s,h,key);return s[key];}
export function prepareMethods(s,h){s.methodOverrides??={};for(const [step,text] of Object.entries(s.prompts||{}))if(!s.methodOverrides['prompt-'+step])s.methodOverrides['prompt-'+step]={text,version:1};for(const key of Object.keys(methodLabels)){const old=s[key];if(!old?.resourceId){const a=methodsFor(h,key).find(x=>x.kind===(old?.mode||'skill'));if(!a)continue;s.methodOverrides??={};if(old?.text&&old.text!==a.text)s.methodOverrides[a.id]={text:old.text,version:old.version||1};selectMethod(s,h,key,a.id);}else s[key]=resolveMethod(s,h,key);}}
export function saveResource(h,value,defaults){const old=h.methodLibrary.find(x=>x.id===value.id);if(old&&(old.kind!==value.kind||old.stage!==value.stage||old.interactionKey!==value.interactionKey))throw Error('已有方法的类别和适用环节不可变更，请新增方法');const name=value.name?.trim(),text=value.text?.trim();if(!name||!text)throw Error('请填写方法名称与内容');if(!['skill','prompt'].includes(value.kind)||value.kind==='skill'&&!methodLabels[value.stage]||value.kind==='prompt'&&!defaults[value.interactionKey])throw Error('请选择有效的类别与适用环节');if(h.methodLibrary.some(x=>x.id!==value.id&&x.kind===value.kind&&x.stage===value.stage&&x.interactionKey===value.interactionKey&&x.name===name))throw Error('同一环节已有此名称');if(value.kind==='prompt'){const required=defaults[value.interactionKey].match(/\{\{\w+\}\}/g)||[];if(required.some(v=>!text.includes(v)))throw Error('缺少必填变量：'+required.filter(v=>!text.includes(v)).join('、'));}const a={...value,id:old?.id||'method-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name,text,version:(old?.version||0)+1,history:old?[...(old.history||[]),{name:old.name,text:old.text,version:old.version}]:[]};if(old)h.methodLibrary[h.methodLibrary.indexOf(old)]=a;else h.methodLibrary.push(a);return copy(a);}
