import {beginText,endText} from './text-loading.js';
import {logJob} from './workflow-store.js';
import {C,$,esc,toast,save,on,methodMarkup,bindMethods,wait} from './studio-ui.js';
import {buildScript,reviewScript,confirmScript,clone} from './workflow-store.js';
let generating=false;
export function scriptPage(){const s=C.s,d=s.scriptDraft,r=s.scriptReport;return `<div class="page-heading"><div><p class="eyebrow">共用步骤 / 剧本</p><h1>剧本工作台</h1><p>生成后自动检查原作贴合度与剧本连贯性。</p></div></div>${!s.selectedNovel?'<section class="panel"><p>先选择小说或输入故事。</p><a class="button primary" href="./creation.html" data-nav="creation">返回创作入口</a></section>':`<div class="script-layout"><section class="panel" id="novel-source"><h2>原小说 · ${esc(s.selectedNovel.title)}</h2><p class="source-novel">${esc(s.selectedNovel.text)}</p><a href="./story.html" data-nav="story">返回修改 / 更换故事</a></section><section class="panel" id="script-work"><div class="panel-header"><h2>剧本 ${d?'v'+d.version:''}</h2><span class="helper">${s.scriptMethod.mode==='skill'?'剧本 skill':'剧本提示词'}</span></div>${d&&(d.snapshot.duration!==s.duration)?'<div class="notice warning">短片规格已变化，请按当前规格重新改编。<button class="button" id="regenerate-script">重新改编剧本</button></div>':''}<label class="field">剧本正文<textarea id="screenplay" ${!d?'disabled':''}>${esc(d?.text||'')}</textarea></label><p class="helper" id="script-save-state" role="status">正文自动保存；生成分镜以此处完整剧本为准。</p><div class="section-end"><span class="helper">质检仅提供建议，是否修改由你决定</span><button class="button" id="recheck-script" ${!d?'disabled':''}>剧本质检</button></div><section class="audit-compact" id="script-quality"><h3>自动质检</h3>${r?`<p>${esc(r.summary)}</p><div class="audit-tags"><span>剧情贴合</span><span>人物情绪</span><span>情节连贯</span></div>${r.issues.map(i=>`<p class="error-text">${esc(i.text)}</p><details><summary>原文依据</summary><p>${esc(i.evidence)}</p></details>`).join('')}<p class="helper">报告绑定剧本 v${r.version}；建议可不采用，保留当前内容也能继续。</p>${r.issues.length?'<button class="button primary" id="repair-script">按报告修复并复检</button>':''}`:'<p role="status">质检报告尚未就绪，你仍可确认当前剧本继续。</p>'}</section><div class="generation-action-row">${methodMarkup('boardMethod')}${d?'<a class="button primary" href="./storyboard.html" data-nav="storyboard" id="to-board">确认并AI生成分镜</a>':'<button class="button" disabled>请先补齐剧本内容</button>'}</div></section></div>`}`;}
let saveTimer;
window.addEventListener("beforeunload",()=>{if(saveTimer)flushScript()});
document.addEventListener("click",e=>{if(e.target.closest("a[data-nav]")&&saveTimer)flushScript()},true);
export function flushScript(){clearTimeout(saveTimer);const ok=save();if($('script-save-state'))$('script-save-state').textContent=ok?'已自动保存':'保存失败，草稿仍保留，请重试';return ok}
export async function startScript(repair=false){if(generating)return;const s=C.s;if(repair&&!s.scriptReport?.issues.length)return;generating=true;s.pendingScript=false;const original=s.scriptDraft?clone(s.scriptDraft):null;const token=beginText(repair?'scriptSuggestion':'script',repair?'#director-quality':'#screenplay');try{await wait(700);if(repair){const copy=clone(s);buildScript(copy,true);s.scriptSuggestion={text:copy.scriptDraft.text,baseText:original.text,baseVersion:original.version};save();}else if(!s.scriptDraft||s.scriptDraft.text===original?.text){buildScript(s);logJob(s,'script',{script:s.scriptDraft});save();endText(token);C.render();const reviewLoading=beginText('scriptReview','#script-quality');await wait(700);reviewScript(s);logJob(s,'scriptReview',s.scriptReport);save();endText(reviewLoading);}}catch(e){toast(e.message)}finally{endText(token);generating=false;C.render();}}
export function bindScript(){const s=C.s;bindMethods();if(s.scriptSuggestion){const box=document.createElement('section');box.innerHTML='<h3>修复建议</h3><p class=source-novel>'+esc(s.scriptSuggestion.text)+'</p><button class=button id=adopt-script-repair>采用此版</button>'; $('script-quality').append(box);on('adopt-script-repair',()=>{const proposal=s.scriptSuggestion;if(s.scriptDraft.text!==proposal.baseText||s.scriptDraft.version!==proposal.baseVersion)return toast('正文已修改，请重新生成建议');s.scriptHistory.push(clone(s.scriptDraft));s.scriptDraft.text=proposal.text;s.scriptDraft.version++;s.scriptSuggestion=null;s.scriptReport=null;s.final=null;save();C.render()})}on('regenerate-script',()=>startScript());if(s.pendingScript&&s.selectedNovel&&!generating){queueMicrotask(()=>startScript());return}if(s.scriptQualityStatus==='running'&&!generating&&s.scriptDraft){generating=true;wait(350).then(()=>{reviewScript(s);logJob(s,'scriptReview',s.scriptReport);s.scriptQualityStatus='ready';save();generating=false;C.render()});}if($('screenplay'))$('screenplay').oninput=e=>{if(s.scriptQualityStatus!=='dirty'){s.scriptHistory.push(clone(s.scriptDraft));s.scriptDraft.version++;}s.scriptDraft.text=e.target.value;s.scriptQualityStatus='dirty';s.scriptReport=null;s.final=null;s.boardConfirmed=0;$('script-quality').innerHTML='<h3>剧本质检</h3><p>内容已修改，可重新检查，也可保留当前版本继续。</p>';clearTimeout(saveTimer);$('script-save-state').textContent='保存中…';saveTimer=setTimeout(flushScript,700);};on('recheck-script',async()=>{const text=$('screenplay').value.trim();if(!text){toast('剧本不能为空');return}s.scriptHistory.push(clone(s.scriptDraft));s.scriptDraft.text=text;s.scriptDraft.version++;s.scriptDraft.needsRepair=text.includes('待检查示例');s.final=null;save();$('recheck-script').disabled=true;const loading=beginText('scriptReview','#script-quality');await wait(700);endText(loading);reviewScript(s);logJob(s,'scriptReview',s.scriptReport);save();C.render()});on('repair-script',()=>startScript(true));if($('to-board'))$('to-board').onclick=e=>{try{if(!flushScript()){e.preventDefault();return}confirmScript(s);s.pendingBoard=true;if(!save())e.preventDefault()}catch(error){e.preventDefault();toast(error.message)}};}
