import {C,$,modal,on,esc,toast,save} from './studio-ui.js';
import {hub,putHub,defaults,steps} from './workflow-store.js';
import {methodLabels,saveResource,stageForStep} from './method-catalog.js';
export function openSettingsMenu(){C.settings('system');}
export function editMethod(id){const a=hub().methodLibrary.find(x=>x.id===id);if(!a)return toast('方法不存在');if(a.kind==='skill')openSkillEditor(id);else openPromptCenter(a.interactionKey,id);}
export function openSkillEditor(id){C.s.methodOverrides??={};let scope=C.s.methodOverrides[id]?'project':'library';const h=hub(),a=h.methodLibrary.find(x=>x.id===id)||{kind:'skill',stage:'writingMethod',name:'',text:''};const d=modal(id?'编辑 Skill':'新增 Skill',`<label class="field">方法名称<input id="skill-name" value="${esc(a.name)}" placeholder="例如：双反转故事法"></label><label class="field">适用环节<select id="skill-stage" ${id?'disabled':''}>${Object.entries(methodLabels).map(([k,n])=>`<option value="${k}" ${k===a.stage?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">生效范围<select id="skill-scope"><option value="library" ${scope==='library'?'selected':''}>Skill库</option><option value="project" ${scope==='project'?'selected':''} ${!id?'disabled':''}>当前项目覆盖</option></select></label><label class="field">Skill 内容<textarea id="skill-text">${esc(scope==='project'?C.s.methodOverrides[id].text:a.text)}</textarea></label>${C.s.methodOverrides[id]?'<button class="text-button" id="reset-skill-override">恢复项目继承Skill库</button>':''}<label class="field">导入 Markdown / TXT<input type="file" id="skill-file" accept=".md,.txt,text/plain,text/markdown"></label><p class="helper">只保存指令文本，不执行文件中的代码。保存后出现在对应工作台的方法菜单；历史任务仍保留旧版本。</p><p class="error-text" id="method-error" role="alert"></p>`,'<button class="button primary" id="save-skill">保存 Skill</button>');$('skill-name').disabled=scope==='project';$('skill-scope').onchange=e=>{scope=e.target.value;$('skill-name').disabled=scope==='project';$('skill-text').value=scope==='project'?(C.s.methodOverrides[id]?.text??a.text):a.text};on('reset-skill-override',()=>{delete C.s.methodOverrides[id];save();d.close();C.render();toast('当前项目已恢复继承Skill库')});$('skill-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>128*1024||!(/\.(md|txt)$/i).test(f.name)){ $('method-error').textContent='请选择不超过128KB的Markdown或TXT';return}try{$('skill-text').value=await f.text()}catch{$('method-error').textContent='读取失败，原内容已保留'}};on('save-skill',()=>{try{const value={...a,stage:$('skill-stage').value,name:$('skill-name').value,text:$('skill-text').value};if(scope==='project'){saveResource(JSON.parse(JSON.stringify(h)),value,defaults);C.s.methodOverrides[id]={text:value.text,version:(C.s.methodOverrides[id]?.version||0)+1};save();}else{saveResource(h,value,defaults);putHub(h);}d.close();C.render();toast('Skill 已保存，方法菜单已更新')}catch(e){$('method-error').textContent=e.message}});}
export function openPromptCenter(step='novel',id=null,newTemplate=false){C.settings('prompts',step,{id,newTemplate});}
export function renderPromptCenter(shell,step='novel',id=null,newTemplate=false){
 C.s.methodOverrides??={};const h=hub();if(!defaults[step])step='novel';const list=h.methodLibrary.filter(a=>a.kind==='prompt'&&a.interactionKey===step);const a=newTemplate?{kind:'prompt',stage:stageForStep(step),interactionKey:step,name:'',text:defaults[step]}:list.find(a=>a.id===(id||C.s.projectPromptBindings?.[step]||C.s.promptBindings?.[step]||h.config.promptBindings?.[step]))||list[0];let scope='library';
 const d=shell('提示词配置',`<div class="field-pair"><label class="field">适用环节<select id="prompt-stage">${Object.entries(steps).filter(([k])=>defaults[k]).map(([k,n])=>`<option value="${k}" ${k===step?'selected':''}>${esc(n)}</option>`).join('')}</select></label><label class="field">提示词模板<select id="prompt-template">${list.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${esc(x.name)}</option>`).join('')}<option value="__new" ${newTemplate?'selected':''}>＋ 新增模板</option></select></label></div><label class="field">生效范围<select id="prompt-edit-scope"><option value="library">系统模板库（与资产库同步）</option><option value="project" ${newTemplate?'disabled':''}>当前项目覆盖</option></select></label><label class="field">方法 / 模板名称<input id="prompt-name" value="${esc(a.name)}"></label><label class="field">提示词内容<textarea id="library-prompt-text">${esc(a.text)}</textarea></label><p class="helper">必填变量：${esc((defaults[step].match(/\{\{\w+\}\}/g)||[]).join('、'))}。保存为新版本，仅影响后续调用。</p><p class="helper">${a.stage?'此模板可从'+methodLabels[a.stage]+'菜单中选用。':'此模板用于该环节的模型调用，不加入故事、剧本或分镜的方法菜单。'}${a.id&&C.s.methodOverrides?.[a.id]?' 当前项目已有独立覆盖，库中更新不会覆盖它。':''}</p><div class="row"><button class="button" id="preview-library-prompt">预览生效模板</button><button class="button" id="reset-method-override" ${!C.s.methodOverrides?.[a.id]?'disabled':''}>恢复项目继承</button></div><pre class="json-output" id="library-prompt-preview" hidden></pre><p class="error-text" id="method-error" role="alert"></p>`,'<button class="button primary" id="save-prompt-template">保存并用于此场景</button>');
 $('prompt-stage').onchange=e=>openPromptCenter(e.target.value);$('prompt-template').onchange=e=>openPromptCenter(step,e.target.value,e.target.value==='__new');$('prompt-edit-scope').onchange=e=>{scope=e.target.value;$('prompt-name').disabled=scope==='project';$('library-prompt-text').value=scope==='project'?(C.s.methodOverrides?.[a.id]?.text??a.text):a.text};
 on('preview-library-prompt',()=>{const el=$('library-prompt-preview');el.hidden=false;const s=C.s,values={storyCount:C.s.storyCount??3,idea:s.idea,instruction:s.topicRequest||'无额外要求',novel:s.selectedNovel?.text||s.novelInput||'[尚未选定故事]',script:s.final?.text||s.scriptDraft?.text||'[尚无剧本]',duration:s.duration+'秒',review:JSON.stringify(s.scriptReport||s.report||{}),shots:JSON.stringify(s.shots),shot:JSON.stringify(s.shots[0]||{}),assets:JSON.stringify(s.shots[0]?.assets||[]),asset:JSON.stringify(s.shots[0]?.assets[0]||{}),style:s.styles[s.styleIndex]?.text,dialogue:s.shots[0]?.dialogue||'',voice:s.finishing.voice,previousFrame:JSON.stringify(s.shots[0]?.previousFrame||null),market:s.market||'中文'};el.textContent=$('library-prompt-text').value.replace(/\{\{(\w+)\}\}/g,(_,key)=>values[key]??'[缺失 '+key+']');});
 on('reset-method-override',()=>{delete C.s.methodOverrides[a.id];if(C.s.projectPromptBindings?.[step]===a.id)delete C.s.projectPromptBindings[step];if(a.id==='prompt-'+step)delete C.s.prompts[step];save();d.close();C.render();toast('当前项目已恢复继承模板库')});
 on('save-prompt-template',()=>{try{const value={...a,name:$('prompt-name').value,text:$('library-prompt-text').value};const test=JSON.parse(JSON.stringify(h));saveResource(test,value,defaults);if(scope==='project'){C.s.projectPromptBindings??={};C.s.projectPromptBindings[step]=a.id;C.s.methodOverrides??={};C.s.methodOverrides[a.id]={text:value.text,version:(C.s.methodOverrides[a.id]?.version||0)+1};if(a.id==='prompt-'+step)C.s.prompts[step]=value.text;save();}else{const updated=saveResource(h,value,defaults);h.config.promptBindings??={};h.config.promptBindings[step]=updated.id;C.s.promptBindings={...h.config.promptBindings};if(updated.id==='prompt-'+step){h.config.defaults??={};h.config.defaults[step]=updated.text;C.s.defaults[step]=updated.text;}putHub(h);}C.s.configVersion++;save();d.close();C.render();toast('提示词已保存，资产库与配置中心使用同一模板')}catch(e){$('method-error').textContent=e.message}});
}
